### ISSUE TITLE
Missing QT_VERSION declaration

### ISSUE THREAD

**Issue by de1001** [copperspice/copperspice#105]
Looks like QT_VERSION is no more defined in cs1.5. It will be a good idea to define this regardless to assist in porting QT based libraries to CS.

P.S. I have ported QScintilla to CS successfully. In the process, undefined QT_VERSION caused havoc.

**Comment by agserm** [comment]
Interesting to hear that not having this macro defined caused serious problems when porting code. Can you tell us what sort of problems you encountered? We could certainly define the QT_VERSION macro, but any value we choose would be incorrect since CopperSpice provides different functionality.

**Comment by de1001** [comment]
Agreed that Copperspice does add more to Qt but on some early day, it came from some specific version of Qt. Retaining that version would be the safest bet.

Scintilla branches code based on QT_VERSION, specifically, in context to features pre version 4 and version 4+. There are number of places in code doing that. I was trying not to modify the code too much to avoid future down integration nightmares. I do plan to pull in future any new features and/or bug fixes. The easiest solution was to define a QT_VERSION macro that was 4+ (since Copperspice at least has everything Qt version 4 had). I guess, I initially took the approach of modifying code and that very soon started looking very scary.

**Comment by agserm** [comment]
I understand your point of view. However, it would be misleading to provide a QT_VERSION macro which would always be incorrect since CopperSpice is not an exact API match for any version of Qt. For example, the container library has changed since QMultiMap does not inherit from QMap. QString is a utf-8 string which represents a sequence of Unicode codepoints. QRegExp has been removed completely and is replaced by QRegularExpression.

In cases like the QRegExp/QRegularExpression conflict, we would have to set QT_VERSION to something in the 5 series. However, not all classes from Qt 5 are supported in CopperSpice, so in some places we only support the Qt 4 API. Defining a QT_VERSION macro might seem helpful at first but in the long run, it will make maintaining your code harder.
