### ISSUE TITLE
Help with building on Ubuntu

### ISSUE THREAD

**Issue by hs-apotell** [copperspice/copperspice#106]
I am having some trouble building my code on Ubuntu 16. The same code builds and run on Windows but not on Unix. I keep getting the following error.

last_data in the context below is declared as "const char*".

```
myimp.cpp:712:21: error: call to constructor of 'QString' (aka 'QString8') is ambiguous
            QString w(last_data);
                    ^ ~~~~~~~~~
include/QtCore/qstring8.h:265:7: note: candidate constructor
      QString8(const QByteArray &str)
      ^
include/QtCore/qstring8.h:281:7: note: candidate constructor
      QString8(CsString::CsString &&other)
      ^
include/QtCore/qstring8.h:276:7: note: candidate constructor
      QString8(const CsString::CsString &other)
```

Compile options I am using -
-g -fPIC -std=c++1z

I have also tried with -std=c++14 as documented on your website but still get the same error.
I have tried both gcc and clang. Same issue.

It's likely something to do with the Unicode string change that was introduced recently.

Appreciate some help resolving this.

**Comment by bgeller** [comment]
Your observation that this issue is related to the changes in QString and our Unicode support is accurate. Since your variable `last_data` is declared as `const char*` you need to instruct QString which encoding the input string is in. The two possibilities in CopperSpice (at this time) are `QString::fromUtf8(last_data)` or `QString::fromLatin(last_data)`.  If you need other encodings you can use the QTextCodec class. The resulting QString will always be UTF-8. 

If you want your string stored in UTF-16 you need to use QString16. The same requirements on input strings apply.

If you have other questions please feel free to ask.

**Comment by DigitalEclairs** [comment]
That raises the question as to why it builds successfully on Windows with MSVS compiler? Is there a compiler flag that I am missing to enable such errors on Windows?

**Comment by agserm** [comment]
It is not clear why you would be seeing different behavior here. Just checking, you are using the same source code version and getting different results on Ubuntu 16.04 versus MSVC? Can you tell us exactly what version of MSVC you are building on so we can test this again?

**Comment by DigitalEclairs** [comment]
Exact same source code on two different platforms.

On Windows -
Microsoft Visual Studio Community 2017 
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026
Microsoft .NET Framework
Version 4.7.03062

On Ubuntu -
clang version 7.0.0-3 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

I tried building with clang on windows as well and that too reports the same errors. Looks like MSVC is just misbehaving. They seem legitimate issues but it would be "nice" all compilers behaved reasonably same.

**Comment by agserm** [comment]
Thank you for the additional information. We will take a look at this next week.

**Comment by agserm** [comment]
Please retest on the current version of CopperSpice and let us know if there is any remaining issue.
