### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by MOZGIII** [copperspice/copperspice#11]
This repo has no readme. It's a bit annoying to google the project's name to learn about it's purpose.
I guess it would be great if there would be at least a description of the project, somewhat like you have on the website.
A full readme, with contributions and stuff would be much better.

Also, the changes that lead from Qt to copperspice are unclear, and it would be great if the history of qt repo would be prepended instead of starting from the bunch of code as an initial commit.

**Comment by fluxer** [comment]
I've added a readme for the sake of CPack as part of the CMake build system integration, see pull request #10.

As far as the changes and history preserving it's not up to me to decide/do that so I can not speak for that.

Cheers!

**Comment by MOZGIII** [comment]
Checked out your fork, having readme is great! Not markdown but at least something, hopefully it'll be merged.
CMake is even better - I'd love to have it instead of autotools!
Btw, any idea on what's the project's current state is? Seems like the development is either stalled or happens behind closed doors.

**Comment by fluxer** [comment]
The readme does not use markdown syntax because, as I mentioned, it's supposed to be used with CMake's CPack functionality that dumps the content of it to the tty from the generated installer which will not look right.

Do not quote me on it but I think that development is behind closed doors, the project has been worked on for a while yet it has been made public kinda recently. Check the following link for more info: http://www.copperspice.com/docs/cs_overview/timeline.html. The fork was done on May 21 2012 and the public release has happened on May 21 2014. Nowdays I see commits being pushed in bulks and tags being created shortly after. You can watch the repository for changes to get an idea of how things happen in future.

I hope that helps, cheers!

**Comment by MOZGIII** [comment]
Got it, thanks.

**Comment by fluxer** [comment]
You are welcome.

**Comment by bgeller** [comment]
Sorry for the very late reply, we were unaware of the comments on GitHub. Our intention was to have all comments posted to our forum, but since this section is here we will make use of it.  

CopperSpice is not a closed project at all and we are sorry if it came across this way. We truly do  welcome all input and contributions. Our focus since CppCon has been a bit more on DoxyPress. We are shifting back to CS and trying to find the right balance. 

We have added our website name on the main page.  I will look into adding a readme file.  

Thanks for understanding, 

Barbara

**Comment by fluxer** [comment]
@bgeller If you go to https://github.com/copperspice and look at the last updated note you will see "Updated 17 hours ago" (as of the time of me writing this), I've seen updates before too without any commits pushed. Your last change is the copperspice repo description but that was not the case for your changes prior to that, I cannot tell what they were but according to GitHub there were some.

Doesn't look like you make your changes public straight away, as I've noted in my comment above. I believe you and @agserm are doing your changes on private repos or something like that and after you think it's time for release you push your changes to the public. Whatever you are doing looks wrong to me as it makes evaluation of the CopperSpice project and getting the latest fixes harder for potential users.

Correct me if I'm wrong, cheers!

**Comment by bgeller** [comment]
I am not a fan of the time indicators GitHub uses. We have made changes at times and yet the notation on this is not always accurate. I updated the description and it took two days for GitHub to email and notify me. Sadly we have no control over this aspect of the project since the emails and dates are controlled by GitHub.

We push changes to GitHub when they pass our CI process and a new feature appears to be working. Ansel and I know that sometimes problems arise, things are reverted, experimental features are added, etc.  It is our belief that developers want changes as soon as possible and users want a stable release. 

Right now with your awesome addition of the cmake build we are going back to review the autotools build. We had a request a few days ago to add a build feature to disable building some of the libraries they did not need. As soon as we have this it will be pushed to GitHub. 

It occurred to me that since you are not seeing nightly changes you might be thinking we are only going to push things monthly. That would indeed be awful. The truth is, we were contracted to make some significant changes to our DoxyPress open source product. This has taken a significant amount of our time and we apologize. 

Thanks for you comments and continued interest. 

Barbara

**Comment by fluxer** [comment]
@bgeller 

> I am not a fan of the time indicators GitHub uses. We have made changes at times and yet the notation on this is not always accurate. I updated the description and it took two days for GitHub to email and notify me. Sadly we have no control over this aspect of the project since the emails and dates are controlled by GitHub.

I'm aware GitHub has some time issues, yet I have not experienced the issues you did. Not that I've received email notification about description change but overall that's not my point. I've only expressed my observation and, as I said, I may be wrong. I will not go into details about my issues with GitHub as that will derail the issue discussed.

> We push changes to GitHub when they pass our CI process and a new feature appears to be working. Ansel and I know that sometimes problems arise, things are reverted, experimental features are added, etc. It is our belief that developers want changes as soon as possible and users want a stable release.

That makes sense, tough, I personally (and I assume other developers too) would like to see where the project is headed as that is nowhere to be seen. For an example, if you are going to work on Wayland support or some fancy new technology in a separate branch it will occur to me that I may be able to use CopperSpice for a personal project in the future and maybe I (and again, someone else) will be more keen on contributing to the CopperSpice project. The users who want stability can fetch the stable releases, say 1.2.1. They are public and I they should, most likely, not pull from experimental branch (say cs-1.2) until a tag has been made (say cs-1.2.0). If they cannot make the right choice for their use cases that's not something you can just overcome but issuing releases from time to time. Plus, if you (both, @bgeller  and @agserm) consider vendors such as Debian where security is critical I think packagers will appreciate too see any changes now if you make it clear what you do change in your commits so that they can incorporate (backport) your bug-fixes and issue new package release.

> Right now with your awesome addition of the cmake build we are going back to review the autotools build. We had a request a few days ago to add a build feature to disable building some of the libraries they did not need. As soon as we have this it will be pushed to GitHub. 

My additions tried to mimic the Autotools build system in any way possible without touching other parts of the project. There was very little documentation, comments, etc. for me to go by and consider what is or should be optional, what you may or may not accept and so on. Thus, only the WebKit component is optional. I suppose that would be easy to implement in the CMake build system - a few if statements for the find_package() calls, same for add_subdictory() based on the strings in BUILD_COMPONENTS and it's done. It will be up to the one who builds CopperSpice to manually override the BUILD_COMPONENTS variable for desired results. I can do that for the CMake build system but someone else will have to take care of the Autotools build system as I am not for of Autotools.

> It occurred to me that since you are not seeing nightly changes you might be thinking we are only going to push things monthly. That would indeed be awful. The truth is, we were contracted to make some significant changes to our DoxyPress open source product. This has taken a significant amount of our time and we apologize. 

I've noticed that from your comments on the forum.

Now, what I say is my and my alone opinion. If I'm the only one who doesn't see the project grow right I can just take a step back and stop wasting your time.

**Comment by bgeller** [comment]
Thanks for the ideas about cmake, we were looking this over today. Ansel has been working on the autotools modifications and some of it is almost ready to push. CI system is churning away. 

We are grateful for any and all comments or suggestions. Please know you are are not wasting our time. This conversation is extremely valuable for us as well as other developers who may read this thread in the future. Are goal is to share out work and have others join us. 

Barbara

**Comment by ahmedcharles** [comment]
The readme exists, so I suppose this can be closed now.

As for github and issues/pull requests, I'm a contributor to multiple different projects and I routinely get emails (notifications) about pull requests for all of them. I don't remember getting issue emails, but that's probably due to none of the projects I work on making use of github for issue tracking.

**Comment by ahmedcharles** [comment]
@agserm I believe this can be closed now.

**Comment by MOZGIII** [comment]
Yes, readme is there, good job.
