### ISSUE TITLE
C# bindings. NuGet packages?

### ISSUE THREAD

**Issue by define-private-public** [copperspice/copperspice#155]
I saw on NuGet there is a package for CopperSpice (https://www.nuget.org/packages/Copperspice/#).  This leads me to believe that there is a C# binding. Though when adding the package to my .NET core project no new namespace have been recognized that I can use.

Are these actually C# bindings or something completely different?

**Comment by bgeller** [comment]
Thanks for your question. As you may know, CopperSpice is a set of cross platform C++ GUI libraries. 

From the Microsoft documentation:  ". . . NuGet package is a single ZIP file with the .nupkg extension that contains compiled code (DLLs), other files related to that code . . . "

There are no C# bindings available at this time for CopperSpice.  In order to use the CopperSpice libraries on Windows with VS you will need MSVC and your project must be written in C++. 

If you have other questions about MSVC please feel free to ask and we will do our best to help you out. 

Barbara

**Comment by define-private-public** [comment]
Okay, this resolves my question.  I remember hearing about this project a few years ago.  I've been a very avid user of Qt in the past, but I also like C#.  Bindings between the two have always been a bit finicky and IIRC it's been because of the MOC.  I guess I got my hopes up :P

Thanks.  P.S. watched your talk about cs_paint about text rendering; loved it.
