### ISSUE TITLE
Fail to build without XML

### ISSUE THREAD

**Issue by ericLemanissier** [copperspice/copperspice#174]
Building copperspice 1.7.1 with `WITH_XML=OFF` errors with:
```
-- Configuring done
CMake Error: INSTALL(EXPORT) given unknown export "CopperSpiceBinaryTargets"
```
on both windows and linux

**Comment by bgeller** [comment]
Yes, CsXml is required if you are building other CS libraries.  It is not required to build CsCore. 

We do not list how to turn off CsXml in our Overview documentation since it is usually always required.  You mentioned this would happen on Windows and Linux, the library would actually would be required on Mac as well.

**Comment by ericLemanissier** [comment]
@bgeller it errors also when building only CsCore
