### ISSUE TITLE
Feature request: CopperSpice namespace

### ISSUE THREAD

**Issue by efedo** [copperspice/copperspice#191]
This is a big request, and I understand that it may not be realistic, but I was wondering whether you have considered moving CopperSpice into its own namespace (and only populating the global namespace in a Qt-compatibility mode?). Qt is rather anachronistic in its use of globals and in the absence of a proper namespace.

The reason that I ask is because I am in the very early stages of creating a helper library to streamline the nesting of external 3D/GUI libraries into Qt. The goal would be to facilitate gradual widget-by-widget migration away from Qt in existing applications. I was hoping to allow embedding of CopperSpice widgets into Qt applications for this purpose, but I am having the darndest time trying to link both Qt and CopperSpice in a single application. Separation of CopperSpice into its own namespace would solve this issue, and would help to bring it in line with modern C++ practices.

**Comment by bgeller** [comment]
You are correct, it is not possible to link an application with both CopperSpice and Qt. There are a lot of reasons, the first is that we no longer use the meta object compiler, moc was removed in CS. All of the functionality for Signal and Slots, Flags, and run time reflection has been maintained in CopperSpice. Classes like QString and QStringView use UTF-8 encoding (rather than UCS-2) which was a major internal change. This means classes like QJson were redesigned to use our new QString implementation. 

CopperSpice makes heavy use of modern C++ in almost every class. As another example, we did a full redesign of the container classes and added STL compatible template parameters. One of the key principles of this project is to use newer constructs and functionality to remove undefined behavior.  For example, the QVariant class was completely changed and the union was removed in favor of std::variant, std::any, and std::optional. 

Putting CS in a namespace would not solve your concern.  There would be conflicting event systems, signals from one library  would conflict with the other library. 

If you are writing a C++ graphics library we strongly suggest you move to CopperSpice now. We have had several companies migrate large codebases in a single afternoon. Since you mentioned you want to move away from Qt it would make sense to do this in one step.  

Have you seen our PepperMill tool and migration documentation?  

Let us know if you have other questions and we will do our best to help you make this transition. 

Barbara

**Comment by efedo** [comment]
Hi Barbara,

Thank you for your speedy and detailed response! I suspected that dual-linking of Qt/Cs might not be realistic, but thought that it was worth asking regardless. I will have to adapt my plans. I am a big fan of your clean and modern CopperSpice design philosophy and hope that you continue to gain converts. I will try porting my applications. The hold-ups might be support for QCustomPlot, embedding of non-OpenGL GPU contexts, and the need to adapt existing Qt widget style sheets (which I would absolutely love to remove). Anyway, I'll give it a whirl. I am just a lowly non-commercial user, though, so don't waste time on me!
Eric

**Comment by agserm** [comment]
You are not a waste of our time, and neither are your questions. We value all our users, commercial or otherwise. Please feel free to contact us (info@copperspice.com or here on GitHub) with any migration questions you may encounter as you begin the porting process.
