### ISSUE TITLE
Please bring qmake and qbs support back

### ISSUE THREAD

**Issue by CretinHo** [copperspice/copperspice#199]
At least qmake, please. You could rename it to csmake, it's not really matter. You could clearly see how simple and beautiful a .pro file is, compared to your dreadful CMakeLists.txt. About simplicity, qmake definitely wins.

**Comment by janwilmans** [comment]
Hi, there, nice of you to take the time to make a suggestion!

About qmake,  I do not see what the advantage is of the .pro file. Can try to describe what convenience you are missing, maybe we can try to make the user experience better?

Is your concern about building CS or is it build building your own application? because in the latter case, you can still do that...

**Comment by CretinHo** [comment]
> Hi, there, nice of you to take the time to make a suggestion!
> 
> About qmake, I do not see what the advantage is of the .pro file. Can try to describe what convenience you are missing, maybe we can try to make the user experience better?
> 
> Is your concern about building CS or is it build building your own application? because in the latter case, you can still do that...

I want to port a Qt app to CS, the Qt app of course using qmake and a .pro file. I use the CMakeLists.txt of Diamond as a reference and my final conclusion is how simple and beautiful the .pro file is and how dreadful the CMakeLists.txt file is.

**Comment by janwilmans** [comment]
If you want to use a .pro file for your project, you can, can't you?

**Comment by CretinHo** [comment]
> If you want to use a .pro file for your project, you can, can't you?

How? I think .pro is Qt specific? So I only have to replace Qt libraries with CS libraries and done?

**Comment by janwilmans** [comment]
I'm not completely sure how to set it up, but I think you can have custom build steps in .pro files? you may need to turn off the usual 'moc' processing, and set paths to use the CS tools such as rcc? Give it a try!

**Comment by CretinHo** [comment]
> I'm not completely sure how to set it up, but I think you can have custom build steps in .pro files? you may need to turn off the usual 'moc' processing, and set paths to use the CS tools such as rcc? Give it a try!

No, thanks.

**Comment by CretinHo** [comment]
Done. CMake is not as dreadful as I think.

**Comment by bgeller** [comment]
@CretinHo, 

As one of the co-founders for CopperSpice I would like to correct a few things and make you a **fantastic offer**.  

First of all, CS never had support for QMake or QBS.  We started with Autotools and them moved to CMake. I will freely admit that all build systems have there issues. However, keep in mind that Qt has moved to CMake since it is one the of the industry standards.  You will see less support of the other build systems in due time and moving to CMake at some point may be required, even by TQC. 

**Great Offer**  You mentioned you have a QMake project file. Email it me and we will personally write a first draft CMake file. You can test it with your project and we will work with you to build your application.  How does that sound?  You get to move to CopperSpice and defer dealing with CMake.  I think  this is a very fair and reasonable offer.  

Barbara
