### ISSUE TITLE
Released binary doesn't work with MSYS2 GCC (11.2.0)

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/copperspice#217]
Copperspice installed by setup-CopperSpice-1.7.2-x64.exe. The error message is like this: THE PROCEDURE ENTRY POINT [SOMETHING I NOT ABLE TO RECALL] COULD NOT BE LOCATED IN THE DYNAMIC LINK LIBRARY LIBSTDC++-6.DLL.

Please test to see if you could reproduce this error. I'm not on my work computer to give you the exact error message. Sorry.

**Comment by bgeller** [comment]
Our CopperSpice Overview documentation specifies that on Windows ( if you are not using MSVC ) you will need to use MSYS.   https://www.copperspice.com/docs/cs_overview/build-win.html

**Comment by bgeller** [comment]
Thank you for your interest in CopperSpice. Our "CS Overview" documentation specifies that on Windows ( if you are not using MSVC ) you will need to use MSYS. A link of where to download is provided on the following page. 

https://www.copperspice.com/docs/cs_overview/build-win.html

We do not recommend using MSYS2 because it is a rolling release and extremely hard to provide binaries. There are numerous components that are not relevant to CS and the packing is cumbersome.

If you decide to use MSYS2 you will need to build CopperSpice from source and then use MSYS2 when building all of your applications. The CopperSpice team continually tries to update our toolchains whenever it is appropriate. Even though MSYS is rather old we have not found any issues with development or deployment. If you do, please let us know so they can be addressed.

**Comment by 3oheicrw** [comment]
> Thank you for your interest in CopperSpice. Our "CS Overview" documentation specifies that on Windows ( if you are not using MSVC ) you will need to use MSYS. A link of where to download is provided on the following page.
> 
> https://www.copperspice.com/docs/cs_overview/build-win.html
> 
> We do not recommend using MSYS2 because it is a rolling release and extremely hard to provide binaries. There are numerous components that are not relevant to CS and the packing is cumbersome.
> 
> If you decide to use MSYS2 you will need to build CopperSpice from source and then use MSYS2 when building all of your applications. The CopperSpice team continually tries to update our toolchains whenever it is appropriate. Even though MSYS is rather old we have not found any issues with development or deployment. If you do, please let us know so they can be addressed.

OK. If switching to MSYS2 (https://github.com/copperspice/copperspice/issues/219) is not a possible choice then what about switch to use winlibs.com build of GCC?

https://github.com/copperspice/copperspice/issues/218

MinGW-builds project is not updated for a while. Winlibs.com builds of MinGW could be used separately from MSYS2 (even though it could be used in conjunction with MSYS2, too). Their builds of MinGW doesn't depends on any particular shells and could be used with any shells you want, including the old MSYS.

**Comment by bgeller** [comment]
You are absolutely free to use any version of MinGW you like since CopperSpice will build with gcc 7.3 or newer. We keep the version on Windows as our baseline to ensure compatibility. The following is a link to the versions of gcc and clang we use in our CI.

https://www.copperspice.com/docs/cs_overview/supported-platforms.html

The minimum version of CMake was just moved to 3.16. I do expect our minimum version of gcc to move to at 8.x in a few months.

**Comment by bgeller** [comment]
> Their builds of MinGW doesn't depends on any particular shells and could be used with any shells you want, including the old MSYS.

I wanted to clarify something which is very important. The version of MinGW we are using does not require MSys. The issue you experienced was a result of using our pre-built binary files with a different compiler. On Windows the C++ standard library will be part of MinGW.  This is what requires using the same version of MinGW when compiling CopperSpice and your C++ application.  

Thank you for this discussion, it has helped us clarify the situation.  We will update our CS Overview documentation to reflect this information.
