### ISSUE TITLE
can CS_SIGNAL macro be simplified ?

### ISSUE THREAD

**Issue by hongnod** [copperspice/copperspice#223]
In the doc, CS_SLOT macro can be omitted, can that thing happen to CS_SIGNAL macro?
```
Note
A slot only needs to be registered with the CS_SLOT macro when it is used from the connect() overload which contains the SLOT() macro. If you are using method pointers the slot does not need to be registered.
```

**Comment by agserm** [comment]
> In the doc, CS_SLOT macro can be omitted, can that thing happen to CS_SIGNAL macro?

Thanks for your question. We have recently updated the API tutorial in this area. 

https://www.copperspice.com/docs/cs_api/signals-slots-c.html

As per the documentation you mentioned, the CS_SLOT() macro is optional. You can use a normal method declaration because in connect() a slot can be a method pointer, function pointer, lambda expression, or function object.

If however you are passing a string or using the SLOT() macro in connect(), then you must use the CS_SLOT() macro in your class declaration. 

The CS_SIGNAL() macro is always required and it is doing multiple things at compile time. This macro contains the signal declaration which in turn triggers the implementation to be created during compile time. 

So the signal implementation is in fact a generated method in the current class. It contains the necessary code to emit “the signal” and through another internal call will invoke the slot. 

I will add that as C++ evolves the CopperSpice team continues to review this code for possible improvements.

Let us know if there are any further questions, glad to explain more details if you are interested.
