### ISSUE TITLE
msys2 clang subsystem compile issues

### ISSUE THREAD

**Issue by ZachBacon** [copperspice/copperspice#229]
So using the source release of copperspice 1.7.3 there's an error within qfilesystemengine_win.cpp on line 649 where clang complains about FILE_ID_INFO being an unknown type name.

```
D:/msys64/home/wowza/copperspice/copperspice-cs-1.7.3/src/core/io/qfilesystemengine_win.cpp:649:7: error: unknown type name 'FILE_ID_INFO'
      FILE_ID_INFO infoEx;
      ^
D:/msys64/home/wowza/copperspice/copperspice-cs-1.7.3/src/core/io/qfilesystemengine_win.cpp:651:78: error: use of undeclared identifier 'FILE_ID_INFO'; did you mean 'SIID_INFO'?
      if (getFileInformationByHandleEx(handle, Q_FileIdInfo, &infoEx, sizeof(FILE_ID_INFO))) { 
                                                                             ^~~~~~~~~~~~      
                                                                             SIID_INFO
D:/msys64/clang64/include/shellapi.h:695:5: note: 'SIID_INFO' declared here
    SIID_INFO = 79,
    ^
2 errors generated.
```

**Comment by ZachBacon** [comment]
I just realized that I should test against current master as well just in case.

**Comment by ZachBacon** [comment]
Yeah master is affected by this, I know it's not exactly a high priority given that gcc and msvc works just fine, however would be worth having it fixed for clang/mingw

**Comment by bgeller** [comment]
Can you let us know if this is something which worked for you when building a prior version of CopperSpice with your exact toolchain. 

On Windows we support building CopperSpice use **MSVC** or **MinGW** as specified in our CS Overview documentation.  If you are using MinGW ( as I do ) then you will need to use the version of MSYS referenced in the docs and on our website:  https://www.copperspice.com/documentation-mingw.html

We do not support msys2 since it is a rolling release that is randomly customized. It is known to have reported incompatible issues. Several attempts were made to work around the build problems and we concluded it was not practical to patch msys2. We consulted with various teams at Microsoft and they share some of our concerns. 

One of our team members did some research and found the best and most productive approach is to build a new version of MSYS with a modern toolchain. This will allow us to release a version of MinGW 9.x and MinGW 10.x at the same time. We anticipate a beta release sometime in June.

**Comment by ZachBacon** [comment]
I haven't built a prior version of copper spice, I'm using a pure clang built mingw git master from [llvm-mingw](https://github.com/mstorsjo/llvm-mingw). But while I respect your decision regarding msys2, I don't necessarily agree with the sentiment, people are going to be using the unrecommended methods regardless. Anyways, I took a look to see what qtbase did in their git, 

https://github.com/qt/qtbase/commit/4ddbfb68f858aee45cf7c33718f16b6c7b5beed7

However it's still registering an issue with FILE_ID_INFO

**Comment by bgeller** [comment]
Sometimes programming choices are influenced by what is possible and practical, which does not always match what we want.  CopperSpice ( like any other library ) has been tested and is known to work on approx 15 different systems.  Please understand that if a developer wants to build using an unsupported tool chain they are free to do so, but it may not work.  

If adding this as a supported platform is something you wish to work on, patches and pull requests are always welcome. If instead, you would like the CopperSpice team to work on this task, please contact us via email to set up a support contract. 

Barbara

**Comment by ZachBacon** [comment]
except clang technically isn't unsupported, what you're doing is throwing out of hand a users choice and dismissing them entirely as wrong. It's the absolutely worst mentality to have in my honest opinion. 

But again, it's just an opinion, neither what your or I said is entirely wrong, and I can see where I may of gotten a bit... passionate to use polite language. That said, I'll keep working on the issue and submit a pull request as I do see value in copperspice, especially using my llvm/clang based mingw setup.

**Comment by bgeller** [comment]
All companies have a scope of support and it is understandable that people may disagree.  Every change we make in our toolchain and code base needs to be tested and this is time consuming.  We are happy to review any pull request which is based on your original work or LGPL 2.1.  

Barbara

**Comment by bgeller** [comment]
Closing this issue since using msys2 is not supported. An updated Windows toolchain ( shell utilities and a newer version of GCC ) are currently being investigated.
