### ISSUE TITLE
Suggestion: A Qt5 compatibility layer

### ISSUE THREAD

**Issue by iahung** [copperspice/copperspice#243]
What about something like Qt5Cs (Qt5 compatibility layer for CopperSpice)? It will greatly help the porting of Qt5 apps to CopperSpice. Implementing a full compatibility layer is impossible. But it's useful to have a helper library like that. Please consider. Thank you.

**Comment by iahung** [comment]
For example, the switch of QString to UTF-8 of CopperSpice when Qt's QString is still UTF-16 caused so much troubles already. Not to mention CopperSpice missing some Qt classes or methods or got these classes or methods renamed.

**Comment by bgeller** [comment]
The internals to the CopperSpice libraries are very different and there is no way to mix and match by either company. Remember, CS does not use a meta object compiler (moc) for the Signal / Slot system. Our implementation of containers is also more advanced giving you better access to the STL algorithms. We use pure C++ for all implementations. 

Have you looked at our migration documentation in the "CS Overview Documentation"?  
https://www.copperspice.com/docs/cs_overview/cs-migration.html

CopperSpice has QString8 and QString16 classes. So if you really need to use UTF-16 you should be using QString16. If you have questions about other migration issues just ask.  

If there is a class you would like to see added please consider a pull request. Since CS is licensed under LGPL 2.1 only functionality up to 5.6 can be integrated into CopperSpice. We can not accept  a PR beyond that point.  

Feel free to tell us exactly what functionality you believe CS needs to accommodate for your current applications.

**Comment by iahung** [comment]
@bgeller It's not simple as just use QString16. Functions don't use QString16 as input. All functions use the input as QString (UTF-16 on Qt), now suddenly QString becomes UTF-8, it can't not causing breakups.

**Comment by janwilmans** [comment]
While non of this is really simple, I'm working on a conversion document and possible will add a small library.
The key thing I wanted is to do a much work as possible before actually converting my build files.
(making all possibly backwards compatible changes first)

This [document ](https://github.com/janwilmans/copperspice-gettingstarted/blob/master/documenation/migration.md)is a work in progresss and honestly, I'm not sure I will even finish it. However, it might give you ideas on how to migrate more smoothly.

**Comment by bgeller** [comment]
> It's not simple as just use QString16. Functions don't use QString16 as input.  

There were multiple places internally in CS where we had to deal with UTF-16 strings, especially when calling a Windows API. Our team has also assisted a lot of projects in  converting many applications and they all work. 

Their QString is not actually UTF-16, it is UCS-2 which is even more primitive. There is a long list of items we fixed including places where they lost surrogates. Using UTF-8 is the absolute right choice and even there programmers have admitted we made the right choice.

We do understand you have a question or some code that is not working. Write up a small sample or post a few lines of code. As one of the maintainers of this project I promise we will help you figure this out. If you decide you want our team to do the conversion this is another option for you.  

Barbara
