### ISSUE TITLE
Can you write an article comparing CopperSpice and the FOX Toolkit?

### ISSUE THREAD

**Issue by chatchoi** [copperspice/copperspice#315]
I found that there is an article comparing CopperSpice and Verdigris on CopperSpice Journal. I would like to see an article comparing CopperSpice and the FOX Toolkit. The advantage of the FOX Toolkit is it's very lightweight, can work without any graphics acceleration, and it's very portable. As I know, CopperSpice can't even work without graphics acceleration. But CopperSpice has an advantage that it could be themed using CSS (in theory, though, I have never seen any CopperSpice applications not in the default theme). Both FOX and CopperSpice relied intensively on macros. `CS_OBJECT` and `FXDECLARE` are very similar...

**Comment by bgeller** [comment]
I do not want to be harsh but some of your observations are simply not accurate. It would be better to ask questions since you are new to CopperSpice. We are happy to help you learn. 

Writing about Verdigris was relevant since this project was based on some of the work in CopperSpice.  The author wanted to see the Meta Object Compiler removed, as did we. 

In order to compare CS with some other project it require spending at least a month or more to study their internals. Otherwise we are just guessing. The term "lightweight" can mean the product offers very little functionality or is too generic. 

Why did you decide that CS can not work without graphics acceleration? On what basis did you reach this conclusion? 

In response to CSS, have you looked at our KitchenSink demo program?  There is an example which uses the style sheet system.  Some developers like this approach and others do not.  

Macros are part of C++ and when used responsibly they can offer a way to create functionality which is not present in the core language. As C++ evolves we might find that some of our macros may not be required.  CopperSpice makes use of templates to ensure type safe signal/slot delivery.  This will most likely never change but with new features in the language we can improve our code base. 

Later this year we will be moving from C++17 to C++20 and several internal implementations will be changed. This is going to be exciting and CopperSpice 2.0 will be that much better. 

Barbara

**Comment by chatchoi** [comment]
> Why did you decide that CS can not work without graphics acceleration? On what basis did you reach this conclusion?

From reading issues on this repository. It could be that I remember it wrong. I didn't bookmark the relevant content. But from what I recall, CopperSpice uses accelerated graphics and can't work without OpenGL.

**Comment by mh466lfa** [comment]
@chatchoi I don't know why you want such a one-sided article like https://journal.copperspice.com/?p=608. Totally dodge the performance issues of CopperSpice that is what really criticized by the article on Vedigris website. What you see is simply people in competing business defending their own products and down play each others. Nothing technical to see here. It seems Vedigris attacked first (2016). CopperSpice posted the defend much later (2022).

Speaking regarding Vedigris, I can only think that their real drawback is their macros are very cumbersome to use and not documented well. You have to look into examples to see how it works. CopperSpice's macros are more close to the original Qt.

**Comment by bgeller** [comment]
> It could be that I remember it wrong. I didn't bookmark the relevant content. But from what I recall, CopperSpice uses accelerated graphics and can't work without OpenGL.

@chatchoi, 

Your information is incorrect and we want to help you learn. OpenGL is an an _optional_ component and *not* required for a normal GUI using widgets. 

Barbara

**Comment by bgeller** [comment]
@chatchoi and @mh466lfa, 

There is a huge back story to Verdigris and the author was actually inspired by the work we did in CopperSpice. There was no animosity between the various teams.  Any notion of conflict is a distortion based on a few uniformed people.  

The idea of Verdigris was to help Qt evolve and move away from their Meta Object Compiler (moc).  When the work he did was rejected he moved on and left the project.  He became a software consultant and our hope is that he is doing well. 

Barbara 



Barbara
