### ISSUE TITLE
Does CopperSpice still support Windows 7?

### ISSUE THREAD

**Issue by mh466lfa** [copperspice/copperspice#317]
And how long could you keep the support for Windows 7? Qt6 has removed support for both Windows 7 and Windows 8. Luckily, there is a fork that added back support for Windows 7/8.  But the future of Qt6 on Windows 7/8 is very uncertain.

**Comment by chatchoi** [comment]
I think they officially only supports Windows 10+. But this will not be a problem, as long as the applications still run on older Windows. This is not the case with Qt6, which is intentionally using API that only available in new Windows.

**Comment by bgeller** [comment]
Windows 7 reached end of life in 2020 and Windows 8 reached end of life in early 2023.  We strongly suggest you upgrade any of your machines using these platforms as they pose a risk due to security issues.  Nether platform is actively supported in CopperSpice.  

It is likely that platform specific changes in CS will inhibit these two versions of Windows as we improve internal functionality. As per our CS Overview documentation our internal CI is run on machines using Windows 10. 

Barbara
