### ISSUE TITLE
How to setup OpenSSL?

### ISSUE THREAD

**Issue by chatchoi** [copperspice/copperspice#318]
I have built my own OpenSSL. Now what I need to do next? Add it to `PATH` or copy the DLL into CopperSpice's `bin` directory? Is only the DLL needed? Or I need the headers, too? If it's the case, where should I put the headers? Please help. Thank you.

p/s: I'm using the prebuilt binary of CopperSpice. I'm not building CopperSpice from source.

**Comment by bgeller** [comment]
Since you have closed this ticket we are unsure if you figured out how to link CopperSpice with OpenSSL.  Please note that using OpenSSL is optional and not required. 

To use OpenSSL you must compile the CopperSpice libraries and include a variable on your CMake command line.  The following is a working example for Windows. 

cmake -G "Ninja"  -DOPENSSL_ROOT_DIR=path-to-openssl-install  \
                             -DCMAKE_BUILD_TYPE=Release  \
                             -DCMAKE_INSTALL_PREFIX=/c/cs_lib  \
                             /c/cs_src
                             
Barbara

**Comment by chatchoi** [comment]
I used to think your CopperSpice binary releases are already built with OpenSSL support enabled and only need me to copy the OpenSSL DLLs (which are not included by default because of legal issues) to enable the use of OpenSSL. It turned out to be wrong. I can't effort building CopperSpice from source so it's a no go to me.

**Comment by chatchoi** [comment]
Do you know a text editor named texteditor.pro? It has built-in support for reading PDF. But the feature is not available by default. People want to use this feature has to download the PDFium DLL themselves. This is very flexible. Why don't you do the same?

**Comment by bgeller** [comment]
We are glad you now understand the binary releases of CS never contained OpenSSL.  Learning is always a good thing.  

I am not sure why you can not "afford" to build CS since it is an open source project and there are no fees. If you meant that your personal computer is too sluggish, then most likely you are going to have issues with build most software.

**Comment by bgeller** [comment]
If you have a question about an editor, this should not be embedded in a thread about OpenSSL. It is also not clear what this has to do with CopperSpice.
