### ISSUE TITLE
Detection of 3rd-party software

### ISSUE THREAD

**Issue by DanOlivier** [copperspice/copperspice#55]
Hi,

I've been looking over the build code and hierarchy, and can't quite understand why there are so many private copies of packages that are commonly available and stable (probably everything under `src/3rdparty`, but especially libjpeg, libtiff, zlib, libpng, sqlite, lfreetype).

I even see two different versions of JavaScriptCore!? (`src/3rdparty/javascriptcore/JavaScriptCore` and `src/3rdparty/webkit/Source/JavaScriptCore`)

Wouldn't it be possible to use `pkg-config` to perform detection of installed packages (on those platforms that support it, or additional cmake modules), and then put the 3rd-parties inside git sub-modules (to allow them to be optional)? I have already started to implement this (as an experiment, and so upgrading to gstreamer-1.0 is on my path).

This implies version checks, and further implies that various platforms will not necessarily be able to satisfy these versioning requirements, but is the answer really to just embed everything? I can list all the benefits, but I gather that it was done this way because the platform in use doesn't have a descent package manager (i.e. Windows).

Thanks

**Comment by agserm** [comment]
Hi Dan,

Thanks for your questions and feedback. Yes, we have inherited some historical baggage in the build process that is in the process of being cleaned up.

It would definitely be preferable on platforms with a functional package manager to pick up all possible third-party libraries from the system. There definitely is some room for improvement using `pkg-config`. I'm not sure the value of moving them to git sub-modules is worth the complexity of sub-module management for this use case though. The third party libraries are for the most part quite small relative to the CopperSpice project.

As you have noted a lot of these bundled packages exist to cope with the lack of these packages from the vendor on Windows and to a lesser extent OS X. The JavaScriptCore package is a bit of a special case since the different versions are used for different purposes. One is used to build the CsScript library, the other is used internally in WebKit, and I believe there are differences between the two. In the future, it seems like the right thing to do is replace both of them with a single copy of v8 but that is obviously a more involved project.

I'm inferring from what you said that you are interested in experimenting with some of these changes and if so, welcome to the team and thank you! We definitely know that the gstreamer upgrade is important and any help we can get in that direction is very much appreciated as well.
