### ISSUE TITLE
need cmake example

### ISSUE THREAD

**Issue by topillar** [copperspice/copperspice#68]
API doc says there is  an sample HelloLunch project， but I can't find it. the kitchensink project does have a cmake  file, but it seems link to CS's source and binary,  cmake it without success. Can you please show us an very simple demo how to use cmake & CS with CS as external package style?

**Comment by agserm** [comment]
HelloLunch is an example to show a comparison between build systems. The text for these files are located in the CS Overview documentation. We provided three different versions for CMake, QMake, and Autotools.

http://www.copperspice.com/docs/cs_overview/sample-cs-cmake.html
http://www.copperspice.com/docs/cs_overview/sample-qt.html
http://www.copperspice.com/docs/cs_overview/sample-cs-autotools.html

Our current binary distribution is built with Autotools. We do plan on releasing a CopperSpice binary built with CMake. Are you trying to use CMake to build KitchenSink with our binary package of CopperSpice? At the moment, you will need to build CopperSpice from source with CMake in order to use CMake with your project. This configuration is tested in our CI system.

If you have any further questions, please let us know.

**Comment by topillar** [comment]
Yes，better use CMake to build self project with released binary package of CopperSpice.
thanks!
